### ISSUE TITLE
Add Moar Graphics to COMPLIANCE.md

### ISSUE THREAD

**Issue by CloudBeard** [defenseunicorns/compliance-md-generator#8]
Creating bar graph and vertical stacked bar graphs functions.
```[tasklist]
### Tasks
- [x] Create Bar function
- [x] Update COMPLIANCE.md to inlcude Bar Graph
- [x] Create Vertical Stacked Bar Function
- [x] Update COMPLIANCE.md to include Stacked Bar Graphs
- [x] Revisit what to do with Pie Charts
- [x] Get feedback on graphs/update colors
```

**Comment by CloudBeard** [comment]
Updated color scheme. All's left is to decide on what 'base' image should be in the compliance.md
